# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: price-api-v1
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221

# you can overwrite defaults here
#  stage: dev
  profile: serverless-admin
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.myBucket}/*'
        - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

custom:
  myBucket: gsahu-custom-bucket
package:
  artifact: target/spring-lambda-serverless-api-1.0.0-lambda-package.zip


functions:
  pricemeapi:
    handler: com.equihealth.core.handler.RestAPIHandler
    events:
      - http:
          path: /price
          method: post

  priceme:
    handler: com.equihealth.core.handler.GenericHandler

